source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.0"
# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# JWT for authentication
gem "jwt", "~> 2.8"

# Active Model has_secure_password
gem "bcrypt", "~> 3.1.7"

# Blueprinter for JSON serialization
gem "blueprinter", "~> 0.11"

# Rack CORS for handling Cross-Origin Resource Sharing (CORS)
gem "rack-cors"

# Rack Attack for rate limiting
gem "rack-attack", "~> 6.7"

# Faraday for making HTTP requests in the testing engine
gem "faraday", "~> 2.9"
gem "faraday-multipart"

# Sidekiq & Redis (used in production, ActiveJob async adapter used in dev)
gem "sidekiq", "~> 7.2"
gem "redis", "~> 5.0"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false

  # RSpec for tests
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails", "~> 6.4"
end

group :test do
  gem "database_cleaner-active_record"
end


